USE [master]
GO

/****** Object:  Database [StudentManagementDB]    Script Date: 4/8/2022 13:10:28 ******/
CREATE DATABASE [StudentManagementDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StudentManagementDB', FILENAME = N'C:\Users\myhp\StudentManagementDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StudentManagementDB_log', FILENAME = N'C:\Users\myhp\StudentManagementDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentManagementDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentManagementDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentManagementDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentManagementDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentManagementDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [StudentManagementDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentManagementDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentManagementDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StudentManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentManagementDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentManagementDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentManagementDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [StudentManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentManagementDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StudentManagementDB] SET  MULTI_USER 
GO

ALTER DATABASE [StudentManagementDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentManagementDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentManagementDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StudentManagementDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentManagementDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StudentManagementDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StudentManagementDB] SET  READ_WRITE 
GO

